version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: dkdapp-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: dkdapp
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2
    container_name: dkdapp-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: